"""Add user relationship to Reservation

Revision ID: 663810119fc5
Revises: 9f0adbcb3640
Create Date: 2022-11-11 12:43:21.192784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '663810119fc5'
down_revision = '9f0adbcb3640'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_reservation_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reservation_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
